### PR TITLE
Add Martin Bean’s site

### PR DESCRIPTION
**Pull request by martinbean**
I have a non-white background. Can I haz in?

### CODE REVIEW

**Comment by martinbean** [comment]
I have a non-white background. Can I haz in?

**Comment by jackmcdade** [comment]
Needs 10% more weird. You're almost there!

**Comment by martinbean** [comment]
@jackmcdade I appreciate my site’s not exactly “rad” by any stretch, but was hoping to be included if something as simple and monochromatic as https://pjrvs.com was included 😕

**Comment by jackmcdade** [comment]
The weird doesn’t have to be visual - you should real Paul Jarvis’ blog. It’s a wild ride!

**Comment by martinbean** [comment]
👎

**Comment by jackmcdade** [comment]
Feel free to submit again! The PR is just invalid. :)

**Pull request closed without merging**
