### PR TITLE
Added my website lorenzobersano.com to the list

### PR DESCRIPTION
**Pull request by lorenzobersano**
Freshly deployed so will probably improve it in the future, but I hope you find some weird layout choices interesting!

### CODE REVIEW

**Comment by jackmcdade** [comment]
I like the funky layout! Happy to add you to the list once you get that blog going :)

**Comment by lorenzobersano** [comment]
Hey Jack! Finally published my first post https://lorenzobersano.com/blog/an-ode-to-geronimo-stilton, hope it's weird enough 🤠

**Comment by jackmcdade** [comment]
Welcome to the weird!

**Comment by lorenzobersano** [comment]
🙌
Will add the links for the webring on the homepage as soon as I can!

**Pull request merged**
