### PR TITLE
leihu, weird enough?

### PR DESCRIPTION
**Pull request by jmathias**
I believe leihu qualifies as a weird site for a lot of reasons. I post a lot of weird drawings and stories, and I redesign constantly, currently on version 67 in 21 years.

### CODE REVIEW

**Comment by jackmcdade** [comment]
Would love to have you! Why did you close?

**Comment by jmathias** [comment]
Sorry, I assumed that no response meant either I wasn't passing the weirdness test, or the project wasn't being updated anymore, and I was doing project clean up yesterday so I closed this one too.

If you want, I can reopen.

**Comment by jackmcdade** [comment]
Yeah sorry about that! I have most notifications disabled otherwise my email is useless. I just check in here from time to time. Let’s do it!

**Comment by jmathias** [comment]
put the ring code back into the site.

**Comment by jackmcdade** [comment]
Fantastic. Love the site man.

Unrelated – do you remember meeting in Nashville, at Paramore Redd like 12 years ago?

**Comment by jmathias** [comment]
Thanks!

Yes of course I remember!

**Comment by jackmcdade** [comment]
Those were good tacos.

**Comment by jmathias** [comment]
I remember it as a pancake breakfast, but maybe I am misremembering?

**Comment by jackmcdade** [comment]
Maybe that too – but definitely went to Local Taco.

**Comment by jmathias** [comment]
That is 100% possible, the PR crew loved going to Local Taco!

**Pull request merged**
