### PR TITLE
you know what would be cool? my website probably

### PR DESCRIPTION
**Pull request by KoolKidz112**
i would like to join this prestigious webring of the world wide what. my website is probably fitting for this because:

1. really long homepage
2. wacky blending mode art (see: wallpaper of vent page and log page)
3. extremely crowded way too much stuff. chat in the bottom right banner ads for other neocities websites at the top normal square ads in the middle quiz results on the bottom marquee of buttons in the middle as well uh among other things
4. weird vents
5. radiohead music nonstop oh god
6. uh i think that's it

### CODE REVIEW

**Comment by jackmcdade** [comment]
HAHAHA definitely has all the 90s vibes! Where's the content though? I'm having a hard time finding what the site is about?

**Comment by KoolKidz112** [comment]
the other stuff is on the sidebar below "ADD MY 88x31 BUTTON TO YO WEBSITE!!!!"
2020-09-23 11_32_38-hoylecake yikers
site's mostly about programming and ramblings, it's a personal site really which i revamped to 1. understand html better and 2. be in a neat community

**Comment by KoolKidz112** [comment]
hi just checkig in. if the site is not eligible thats totally fine with me

**Comment by jackmcdade** [comment]
Maybe just a *little* bit too random or unfocused. Thanks though! <3

**Pull request closed without merging**
